FROM alpine:latest

# Use edge repos to have up-to-date Tinyproxy
RUN sed -i "s/\/alpine\/v.*\//\/alpine\/edge\//g" /etc/apk/repositories
RUN apk update --no-cache && apk upgrade --no-cache
RUN apk add --no-cache tinyproxy
USER tinyproxy

ENTRYPOINT tinyproxy -d -c /etc/tinyproxy.conf
